# Generated by Django 4.2.13 on 2026-05-23 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceregularization",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceregularization",
            name="attendance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regularization",
                to="attendance.attendance",
            ),
        ),
        migrations.AddField(
            model_name="attendanceregularization",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="attendanceregularization",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employees.employee"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.shift",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("company", "employee", "date")},
        ),
    ]
