# Generated by Django 4.2.13 on 2026-05-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_extra_fields'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('company', 'module', 'action')},
        ),
    ]
