# Generated by Django 4.2.13 on 2026-05-23 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("current_designation", models.CharField(blank=True, max_length=255)),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "current_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notice_period_days", models.PositiveSmallIntegerField(default=30)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("vacancies", models.PositiveSmallIntegerField(default=1)),
                ("employment_type", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("min_experience_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_experience_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("on_hold", "On Hold"),
                            ("filled", "Filled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.designation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Screen"),
                            ("video", "Video Call"),
                            ("in_person", "In Person"),
                            ("technical", "Technical"),
                            ("hr", "HR Round"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("meeting_link", models.URLField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        related_name="interviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="recruitment.jobpost",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("company", "job_post", "email")},
        ),
    ]
