# Generated by Django 4.2.13 on 2026-05-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/logos/"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_employees", models.PositiveIntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text='e.g. ["Monday","Tuesday","Wednesday","Thursday","Friday"]',
                    ),
                ),
                ("work_start_time", models.TimeField(default="09:00")),
                ("work_end_time", models.TimeField(default="18:00")),
                (
                    "weekly_off_days",
                    models.JSONField(
                        default=list, help_text='e.g. ["Saturday","Sunday"]'
                    ),
                ),
                ("late_mark_after_minutes", models.PositiveIntegerField(default=15)),
                (
                    "half_day_hours",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
                ),
                ("payroll_processing_day", models.PositiveSmallIntegerField(default=1)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=4),
                ),
                ("probation_period_days", models.PositiveIntegerField(default=90)),
                ("notice_period_days", models.PositiveIntegerField(default=30)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_settings",
            },
        ),
        migrations.CreateModel(
            name="CompanyHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_holidays",
                "unique_together": {("company", "date")},
            },
        ),
    ]
